package org.example.TCP.enums;

public enum RequestType {
    LOGIN, REGISTER,
    GET_ALL_USERS,BUN_USER,
    ADD_ROLE_MANAGER,DELETE_USER,
    UPDATE_ACCOUNT,ADD_PROJECT,
    GET_ALL_PROJECTS,ADD_PATENT,
    ADD_EQUIPMENT,GET_ALL_PATENTS,
    DELETE_PATENT,GET_ALL_EQUIPMENT,
    DELETE_EQUIPMENT,UPDATE_PATENT,
    UPDATE_EQUIPMENT,GET_PROJECT_BY_ID
}
